"""Desktop shortcut that starts the helper AND opens the app.

One double-click has to do both: a shortcut that starts a background process
and leaves you staring at nothing is not a shortcut to anything.

Batch scripts are full of % signs (%~dp0, %ERRORLEVEL%), so nothing here uses
%-formatting — f-strings and concatenation only. That collision is exactly what
broke the first version of this file.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import paths                      # noqa: E402
IS_WIN = os.name == "nt"


def config() -> dict:
    try:
        return json.loads((paths.data_dir() / "config.json").read_text("utf-8"))
    except Exception:
        return {"port": 8765, "token": ""}


def make_open_script(cfg: dict) -> Path:
    """Start the helper if it is not already answering, wait until it is, then
    open the browser. The wait matters: opening too early shows a dead page."""
    path = HERE / ('open-app.cmd' if IS_WIN else 'open-app.sh')

    # The environment is in the data folder, not beside this script - it moved
    # out so updates could not delete it. This generator used to hardcode the
    # old location, which meant every run of setup overwrote the working
    # launcher with a broken one: the desktop shortcut and the autostart entry
    # both go through this file, so setup was re-breaking both, every time.
    #
    # Same order as paths.py: data folder first, then beside the code for an
    # installation part-way through moving.
    if IS_WIN:
        lines = [
            '@echo off', 'setlocal', 'cd /d "%~dp0"',
            'rem  Generated by make_shortcut.py. The lookup order matches',
            'rem  worker\\paths.py - change both together.',
            'set "PY=%LOCALAPPDATA%\\Amazon Cash Planner\\venv\\Scripts\\python.exe"',
            'if defined FBA_DATA_DIR set "PY=%FBA_DATA_DIR%\\venv\\Scripts\\python.exe"',
            'if not exist "%PY%" set "PY=%~dp0venv\\Scripts\\python.exe"',
            'if not exist "%PY%" (',
            '  echo.',
            '  echo   The helper is not set up on this computer yet.',
            '  echo   Open Amazon Cash Planner and press "Set up the helper",',
            '  echo   or run: %~dp0SETUP.cmd',
            '  echo.',
            '  if not defined FBA_NONINTERACTIVE pause',
            '  exit /b 1',
            ')',
            '"%PY%" "%~dp0launch.py" %*',
            'if not errorlevel 1 exit /b 0',
            'echo Launch failed. Run SETUP.cmd or DIAGNOSE.cmd.',
            'if not defined FBA_NONINTERACTIVE pause', 'exit /b 1']
        path.write_bytes(('\r\n'.join(lines) + '\r\n').encode('utf-8'))
    else:
        data = str(paths.data_dir())
        path.write_text(
            '#!/bin/sh\n'
            'cd "$(dirname "$0")"\n'
            '# Same order as paths.py: data folder first, then beside the code.\n'
            'PY="${FBA_DATA_DIR:-%s}/venv/bin/python"\n'
            '[ -x "$PY" ] || PY="venv/bin/python"\n'
            'exec "$PY" launch.py "$@"\n' % data)
        path.chmod(0o755)
    return path


def desktop_dir() -> Path | None:
    for candidate in (
        Path(os.environ.get("USERPROFILE", "")) / "Desktop",
        Path(os.environ.get("OneDrive", "_")) / "Desktop",
        Path.home() / "Desktop",
    ):
        if str(candidate) != "_" and candidate.exists():
            return candidate
    return None


def main() -> int:
    cfg = config()
    opener = make_open_script(cfg)

    if not IS_WIN:
        print("      launcher: " + str(opener))
        print("      (drag it to your dock or desktop if you want it there)")
        return 0

    desk = desktop_dir()
    if desk is None:
        print("      could not find your Desktop.")
        print("      Double-click this instead: " + str(opener))
        return 1

    lnk = desk / "Amazon Cash Planner.lnk"
    ps = (
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut('" + str(lnk).replace("'", "''") + "');"
        "$s.TargetPath='" + str(opener).replace("'", "''") + "';"
        "$s.WorkingDirectory='" + str(HERE).replace("'", "''") + "';"
        "$s.Description='Start the helper and open the Amazon Cash Planner';"
        "$s.WindowStyle=1;"
        "$s.IconLocation='shell32.dll,13';"
        "$s.Save()"
    )
    try:
        subprocess.check_call(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
            stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    except Exception as exc:
        print("      could not create the shortcut: " + str(exc))
        print("      Double-click this instead: " + str(opener))
        return 1

    if not lnk.exists():
        print("      the shortcut did not appear on your Desktop.")
        print("      Double-click this instead: " + str(opener))
        return 1

    print("      shortcut: " + str(lnk))
    return 0


if __name__ == "__main__":
    sys.exit(main())
